### ISSUE TITLE
Publish releases to npm

### ISSUE THREAD

**Issue by tnightingale** [Turbo87/leaflet-sidebar#15]
Would be useful to see your releases published on npm so it can be easily used with [Browserify](http://browserify.org/).

**Comment by miccferr** [comment]
Hallo guys,

just jumping into the discussion ;)
I have to agree to @Turbo87 in being skeptical first, but after a bit of reading&experimenting with/about npm i feel too, like @zedd45 , that this is a much clearer way to handle dependencies and external scripts..so..Is this horse dead or alive? :stuck_out_tongue: 
I mean, having it on npm would truly be great!
But as I said, I understand both points of view..
Cheers!

**Comment by Turbo87** [comment]
@miccferr lately I've been working with browserify and [webpack](http://webpack.github.io/) at my dayjob and I'm starting to understand how things should be published to npm when used with tools like that. unfortunately I don't have much time at the moment for it though...

**Comment by miccferr** [comment]
@Turbo87 I understand completely :+1:
I just wanted to second @tnightingale and @zedd45 request since it seems like a useful implementation to an already amazing plugin.
Thanks for your quick reply, though.
Cheers!

**Comment by zedd45** [comment]
@Turbo87 I can look into publishing this to NPM this week, if you'd like.

**Comment by Turbo87** [comment]
sure, feel free to propose a good solution!

**Comment by zedd45** [comment]
I've been swamped this week, but I should be able to get to this early tomorrow.

**Comment by zedd45** [comment]
@Turbo87 this has been done. 
https://docs.npmjs.com/getting-started/publishing-npm-packages

Published Package:
https://www.npmjs.com/package/leaflet-sidebar
