### ISSUE TITLE
does not work with HTML5

### ISSUE THREAD

**Issue by nekromoff** [Turbo87/leaflet-sidebar#29]
when HTML5 declaration is used, blank screen is displayed on calling this library.
when anything is put in front of the declaration such as (invalid code BTW):
```
<span style="display:none;"></span><!DOCTYPE html>
<html lang="en">
```
it will work OK.

**Comment by Turbo87** [comment]
https://github.com/Turbo87/leaflet-sidebar/blob/master/examples/index.html#L1

I have no idea what you are talking about...
