### ISSUE TITLE
Many markers

### ISSUE THREAD

**Issue by lilicipute** [Turbo87/leaflet-sidebar#30]
Hi,

Thank you for this great sidebar plugin.

I would like to know how to create sidebars link to each markers.
I created new markers and when I click on it the new sidebar (2) opens back the sidebar 1 (instead of show hover). Is that possible to close the open sidebar and we click on a new marker ?

Thx in advance,

**Comment by lilicipute** [comment]
Just find this but not really to use when we have a lot of markers/sidebars

        var marker = L.marker([51.2, 7]).addTo(map).on('click', function () {
        if(sidebar2.isVisible())
            sidebar2.hide();
        if(sidebar3.isVisible())
            sidebar3.hide();
        sidebar.toggle();
        });
		
        var marker2 = L.marker([51.2, 7.3]).addTo(map).on('click', function () {
        if(sidebar.isVisible())
            sidebar.hide();
		if(sidebar3.isVisible())
            sidebar3.hide();	
		sidebar2.toggle();
        });

        var marker3 = L.marker([51.2, 7.6]).addTo(map).on('click', function () {
        if(sidebar.isVisible())
            sidebar.hide();
		if(sidebar2.isVisible())
            sidebar2.hide();
        sidebar3.toggle();
        });

**Comment by Turbo87** [comment]
@lilicipute you shouldn't create multiple sidebars. just use one sidebar and adjust the content dynamically via javascript. have a look at https://github.com/Turbo87/leaflet-sidebar/blob/master/examples/listing-markers.html to see how it's done.

**Comment by Kevingarvey20** [comment]
Hello, thanks again for this code i was able t implement the side bar into my map. But i'm also having issues with the having multiple sidebars for specific markers on the map i currently have one side bar for on marker but shows up for the other markers. but  will like to have just one assigned sidebar to a marker.
[Untitled 3.docx](https://github.com/Turbo87/leaflet-sidebar/files/3811067/Untitled.3.docx)
