### ISSUE TITLE
Plugin does not work with twitter-bootstrap button dropdown

### ISSUE THREAD

**Issue by vamsiampolu** [Turbo87/leaflet-sidebar#31]
I added a dropdown from twitter bootstrap to the sidebar,I found that the dropdown will not open.

The markup looks like this:

       	<div id="sidebar">
			<div class="dropdown">
				<button class="btn btn-default dropdown-toggle" type="button" id="query-layer-select" data-toggle="dropdown">
					Select Layer<span class="caret"></span>
				</button>
				<ul class="dropdown-menu" role="menu" aria-labelledby="query-layer-select">
					
						<li role="presentation">
							<a href="#" role="menuitem" tabindex="-1">NEW YORK</a>
						</li>
					
						<li role="presentation">
							<a href="#" role="menuitem" tabindex="-1">HEATHROW</a>
						</li>
					
						<li role="presentation">
							<a href="#" role="menuitem" tabindex="-1">LONDON</a>
						</li>
					
						<li role="presentation">
							<a href="#" role="menuitem" tabindex="-1">PARIS</a>
						</li>
					
						<li role="presentation">
							<a href="#" role="menuitem" tabindex="-1">BERLIN</a>
						</li>
					
				</ul>
			</div>
		</div>

I have set up a plunk here http://plnkr.co/edit/YjBx47
Try running it in full screen

**Comment by guillaumegmt** [comment]
@vamsiampolu how did you deal with it? Thanks.

**Comment by fab-girard** [comment]
Hello,
Like you I'm trying to use leaflet-sidebar and bootstrap dropdown menus inside... but it's not working because of 'stopPropagation' click event used in leaflet-sidebar code... I understand why there is this code in sidebar plugin (prevent to call action for click if it is described for the map when you click on sidebar) but how to use bootstrap drop down menus in that case ?

Regards,
Fabien

**Comment by adriennn** [comment]
I am looking at the same problem here. If you look at [this file](https://github.com/humitos/osm-pois/blob/master/web/assets/js/leaflet-sidebar.js) you will see that the author has discarded all instances of stopPropagation and dropdowns display fine. See a live example [here](http://upoi.org/#comments) (click the "iniciar session" dropdown menu), of course, this is not the bootstrap plugin - it's all generated by disqus - but it shows it works.

**Comment by adriennn** [comment]
This is a fix for showing bootstrap toggles and dropdowns, one needs to do two things: 

1. delete line 64 in L.Control.Sidebar.js :

```javascript
on(content, 'click', stop)
```
2. The single clicks still go through to the map layer which can prevent the proper functionality in the active sidebar so one need to stop listening to map click event when the sidebar is visible:

```javascript
sidebar.on('shown', function () {
        map.off('click', yourClickFunction);
    }); 
   
sidebar.on('hidden', function () {
        map.on('click', yourClickFunction);
    }); 
```

hth

**Comment by Turbo87** [comment]
@adriennn unfortunately now you can't use any clicks on the remaining part of the map that isn't covered by the sidebar...

**Comment by adriennn** [comment]
@Turbo87  Yeah that's the price to pay, but it's good enough for me. I don't need to interact with the map while the sidebar is shown - and anyway, for mobile applications the sidebar covers the map (small screens) so there's no need to actually click on the map :)

I was wondering if you are going to port the plugin to Leaflet 1.0 and perhaps fix this issue? cheers for the plugin!

**Comment by Turbo87** [comment]
@adriennn my focus is on https://github.com/Turbo87/sidebar-v2 since I actually use that myself, but if anyone wants to port it I'd be happy to merge it

**Comment by adriennn** [comment]
@Turbo87  that's a pretty good incentive to move to the v2 but from what I tried on jsfiddle the bootstrap dropdown didn't drop? Anyway, I'll have to look at all this when leaflet 1.0 is out so I can see what's what; from what I saw 1.0 is gonna be terrific and it didn't look like the updated api breaks much, so sidebar-v1 might still work there..

**Comment by vamsiampolu** [comment]
I actually used `select` instead of the `dropdown`(which is not always appropriate) but in my case it was.

**Comment by adriennn** [comment]
@vamsiampolu the bootstrap selects don't work either. One could also stop listening to click events on the map while the sidebar is shown (you could still click on markers and other elements). But if you have a better idea I'm all ears.

**Comment by Turbo87** [comment]
@adriennn since you seem to be pretty active: could you prepare a jsfiddle, gist or something for me that demonstrates the problem? maybe I can figure something out. I'm having a hard time believing that this is so problematic ;)

**Comment by adriennn** [comment]
[here](https://jsfiddle.net/adriennn/9w824u4b/2/) you go. 
thanks for looking into this :-)

**Comment by Turbo87** [comment]
@adriennn I've fixed the issue by using the internal `_fakeStop()` method of leaflet and release it as v0.1.7. If there are still issues with this please let me know.

**Comment by adriennn** [comment]
@Turbo87 well thank you so much sir. It works (and the multiselects display fine as well - not sure why they don't show up nicely in the fiddle). cheers to you.

**Comment by Turbo87** [comment]
about the selects: the selects CSS file was missing from the jsfiddle

**Comment by adriennn** [comment]
okay, it seems that now fakeStop is messing with other elements:
```
.on(content, 'mousedown', fakeStop)
```
If I select some text inside the sidebar with, it will move the map below as well. So I stick to the full stop for now.

**Comment by Turbo87** [comment]
@adriennn could you check if http://turbo87.github.io/leaflet-sidebar/examples/bootstrap.html works for you? I've pushed another patch that should fix your issue.

**Comment by adriennn** [comment]
yes it works fine with using stop. thanks!
