### ISSUE TITLE
z-index 

### ISSUE THREAD

**Issue by reyemtm** [Turbo87/leaflet-sidebar#36]
I am needing to set the close button's z-index in leaflet-beta-2 to 800 to show up. Everything else seems to work fine.

**Comment by zedd45** [comment]
Looks like this issue may be related to #51. I think we can make an adjustment for this.  I am not sure what changed, but this is a fairly easy fix, I believe.

**Comment by zedd45** [comment]
@Turbo87 should we bump the `z-index` value, or is it preferable to let users specify a higher `z-index` in their own CSS file for the selector: `.leaflet-sidebar .close`?

**Comment by themacboy** [comment]
same problem here. I have solved the problem with:

.close {
z-index: 800 !important;
}

**Comment by serl** [comment]
It looks like the z-index for .leaflet-control was changed from 7 to 800 since v1.0.0: https://github.com/Leaflet/Leaflet/commit/64f7ef58cbcc9b6cfc52a10c21a1a41876ee5e68
Apart from that, this library works perfectly with the last version of Leaflet (v1.7.1) 🥰

**Comment by zedd45** [comment]
Good call @serl ; I'll make the update.  Looks like this one fell off the radar for a while.
