### ISSUE TITLE
Basic example not working on jsfiddle

### ISSUE THREAD

**Issue by a1an77** [Turbo87/leaflet-sidebar#40]
Hi, trying to investigate some unexpected event handling behaviour I set up a jsfiddle. There even basic functionality seems to be broken: https://jsfiddle.net/A1an/kt0fkvxc/

I get the "Hello World" text on top left of the map, then, even though the events seem to be fired and handled correctly, nothing changes in the map and the panel is not shown at all. Any idea what could be going wrong?

**Comment by Turbo87** [comment]
````
Uncaught ReferenceError: L is not defined
````

**Comment by adriennn** [comment]
you have two issues here, first, you are using raw github addresses, that's not gonna work in jsfiddle (see [this thread](http://stackoverflow.com/a/21670862/2842348) on SO ) and second there are some relatively fresh issues with leaflet's cdn (see[ this thread](https://github.com/Leaflet/Leaflet/issues/4080) ) so you need to use another cdn (e.g. https://cdnjs.com/libraries/leaflet/)

**Comment by Turbo87** [comment]
@adriennn thanks!

**Comment by a1an77** [comment]
So rawgithub.com is indeed the way to go for CSS, even though I guess a bit more flexibility could be built into jsfiddle itself to avoid such issues. Regarding the leaflet's cdn issue I'm not sure I got it right: if it about the certificate issue I solved it by opening the link directly in Firefox and from there adding a permanent exception to the security warning. Is there more about it?

That said, now I get an unexpected behaviour again since the panel covers the entire lower right quadrant as soon as it is displayed and no further action can be done. Is that expected or should I file an issue about proper sizing of the panel within small maps?

Many thanks

**Comment by adriennn** [comment]
if your viewport is smaller than a certain amount of pixels, the default css rules will make that the sidebar overlays the entire width of your viewport, so you need to override the css if you don't want this behavior. As for the close button, you need to add the option:

`L.control.sidebar('sidebar', {position: 'left', closebutton: 'true'});`

I don't know what's the deal with the leaflet cdn, but jsfiddle doesn't seem to like it sometimes, for some versions of leaflet. If you call it from your localhost it will be just fine, or use a local file.

Note that [Stackoverlfow](http://stackoverflow.com/questions/tagged/leaflet) is a better place to look for answers / ask questions if you have any more issues.

**Comment by a1an77** [comment]
Indeed for Q&A I would prefer SO, however I am trying to find out if I discovered a bug (I changed the title accordingly but I can open a new issue if you prefer) :-)

In the fiddle I used an object to hold the options and tried both with 'true' and true (without quotes), the close button does not show up anyway.

panel_options = {
        closeButton: 'true',
        position: 'left',
        autoPan: false
    };

**Comment by a1an77** [comment]
And I just noticed issue #36 is already mentioning it, so this one solves as duplicate. Thanks for helping meanwhile.
