### ISSUE TITLE
as I can block the sidebar?

### ISSUE THREAD

**Issue by dejoramo** [Turbo87/leaflet-sidebar#43]
as I can block the sidebar?
if you click the map, the sidebar is hidden.
I just want to hide if I click the x.

**Comment by dejoramo** [comment]
how could block the sidebar?

**Comment by Turbo87** [comment]
> if you click the map, the sidebar is hidden.
> I just want to hide if I click the x.

you will have to remove the following lines: https://github.com/Turbo87/leaflet-sidebar/blob/master/examples/index.html#L82-L84
