### ISSUE TITLE
Hold Sidebar v2 width when printing

### ISSUE THREAD

**Issue by jerryhall** [Turbo87/leaflet-sidebar#44]
Thanks for this plugin. I've been waiting to use it and finally am able. My goal is to put an extensive legend in the sidebar. Could you tell me if there's a way I can restrict the width of the sidebar when doing a print-screen? When I try the sidebar expands the full width of the map. Thanks!

**Comment by Turbo87** [comment]
> when doing a print-screen

you mean you're trying to print the page in a browser?

**Comment by jerryhall** [comment]
Now that you ask that sounds foolish eh? I'm working to install some kind of printer/pdf plugin so thanks for that question.

**Comment by Turbo87** [comment]
you have two options if you want to make this work:

- use a `print` [media query](https://developer.mozilla.org/de/docs/Web/CSS/@media) to make sure the sidebar has the correct width when printed
- tell the printer plugin to use a bigger resolution, as the sidebar only goes fullscreen if the page width is below 768px
