### ISSUE TITLE
sidebar blocks other buttons

### ISSUE THREAD

**Issue by kaio328** [Turbo87/leaflet-sidebar#45]
Hey,

while everything works fine on local devices (firefox/chrome), i got the following problem on mobile devices:
When the sidebar is active and displayed on the map, i cant click any of my other buttons (f.e. locate button, search button). But im able to pan through the map. Any solution to fix this  prob?

Greetz from Germany

**Comment by Turbo87** [comment]
@kaio328 without any example code I can't help you. do you have a reproduction somewhere?

**Comment by kaio328** [comment]
mh unfortunatly not :/

is there any quick fix via stylesheet? i tried stuff like sidebar.BringToBack(); and removed line 65-71 from L.Control.Sidebar.js !
But the sidebar still blocks everything except panning through the map.

**Comment by adriennn** [comment]
if you can put an example on the [leaflet playground](https://playground-leaflet.rhcloud.com/?html,output) that would help.

**Comment by kaio328** [comment]
solved it! was a prob with css. after fixing position of my sidebar the buttons are no longer blocked!
