### ISSUE TITLE
code for many markers

### ISSUE THREAD

**Issue by kubs3** [Turbo87/leaflet-sidebar#46]
Im a beginner in leaflet and html coding. Im trying to create a map with this sidebar plugin ( https://github.com/turbo87/leaflet-sidebar/)I can make a map with many markers and plugin from "demo example", but I don't know, how to create a "dynamic" content in slidebar which shows atributes from each marker separately. Thanks for anythink ! Jakub

My simple code:
```html
<script>
    var map = L.map('map');

    L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 18,
        attribution: 'Map data &copy; OpenStreetMap contributors'
    }).addTo(map);

    var sidebar = L.control.sidebar('sidebar', {
        closeButton: true,
        position: 'left'
    });
    map.addControl(sidebar);
    sidebar.setContent('aaaaaaa');   

    setTimeout(function () {
        sidebar.show();
    }, 500);
    var marker = L.marker([49.46, 17.11]).addTo(map).on('click', function () {
        sidebar.toogle()
        marker.bindPopup("<b>Hello world!</b><br />I am a popup.").openPopup();
    sidebar.setContent('aaaaaaa');   

    map.on('click', function () {
        sidebar.hide();
    });
    });

    map.setView([49, 17], 5);
</script>
```

**Comment by Turbo87** [comment]
you need to call `setContent()` with the contents for the marker you clicked. you example has only one marker and on the `click` event handler you already correctly call `setContent()`.
