### ISSUE TITLE
Npm installs a different version

### ISSUE THREAD

**Issue by CGastrell** [Turbo87/leaflet-sidebar#48]
Hi, I love this control, nice and simple.

I have this issue though, when I check the code on the repo there is this method:
```javascript
setContent: function (content) {
    setContent: function (content) {
        var container = this.getContainer();

        if (typeof content === 'string') {
            container.innerHTML = content;
        } else {
            // clean current content
            while (container.firstChild) {
                container.removeChild(container.firstChild);
            }

            container.appendChild(content);
        }

        return this;
    },
```
which does exactly what I need. But after installing via `npm install leaflet-sidebar` the mentioned method looks like this:
```javascript
    setContent: function (content) {
        this.getContainer().innerHTML = content;
        return this;
    },
```

Is there a way you can sync `npm` version to this one? Or shall I go for the _install from repo_ option?

**Comment by zedd45** [comment]
Could you post the version you have in your `package.json`, as well as the output of `npm i -v`? 

It looks like the last publish was about a year ago.

**Comment by zedd45** [comment]
Actually, it looks like we've had about 6 commits to `master` since the [`v0.1.9` release](https://github.com/Turbo87/leaflet-sidebar/releases/tag/v0.1.9).

@Turbo87 any objections to me bumping `packge.json` a minor release, and `npm puslish`ing this?

**Comment by Turbo87** [comment]
> any objections to me bumping packge.json a minor release, and npm puslishing this?

not at all. that would be great, thanks!

could you add me as an owner to the npm package? then I could setup auto publish via TravisCI too.

**Comment by zedd45** [comment]
Absolutely! Thanks, @Turbo87

**Comment by zedd45** [comment]
@Turbo87 I've attempted to add you via the cli for npm, as well as the web interface.  npmjs.com didn't act like it found a user with your email, nor your github handle, but the cli seemed OK to add you with `turbo87`.  Would you check if that's working, and if not, we can handle that outside of this issue? 

I've also submitted a PR for a version bump you'll need to accept, and I'll publish the latest version.

**Comment by CGastrell** [comment]
Thank you guys for your time and effort :)

**Comment by zedd45** [comment]
Thank you for identifying the issue.

**Comment by Turbo87** [comment]
> Would you check if that's working

seems to work great, thanks! :)

**Comment by zedd45** [comment]
Published!
