### ISSUE TITLE
Leaflet 1.1.0. Geojson layer. 'Sidebar will be hidden'

### ISSUE THREAD

**Issue by mykolakozyr** [Turbo87/leaflet-sidebar#49]
I'm using Leaflet 1.1.0 and want to toggle sidebar while clicking on features from .geojson layer. I currently work with polygon objects. 
open sidebar (demo version):

```
         function openSidebar(e) {
            sidebar.toggle();
        }
```
defining OnEachFeature:
```
        function onEachFeature(feature, layer) {
            layer.on({
                mouseover: highlightFeature,
                mouseout: resetHighlight,
                click: openSidebar
            });
        } 
```
open .geojson:
```
        var otgLayer = L.geoJson(otg, {
            style: regStyle,
            onEachFeature: onEachFeature,
        }).addTo(map)
```

While clicking on feature, there is the following in the console:

> Sidebar will be visible.
> Sidebar will be hidden.

The sidebar works fine with Leaflet 0.7 when it is a .geosjon polygon
The sidebar works fine with Leaflet 1.1.0 when it is a marker

**Comment by mykolakozyr** [comment]
the 'hide' function for .geojson layer raises by this part:
```
        map.on('click', function () {
            sidebar.hide();
        })
```

**Comment by mykolakozyr** [comment]
Seems like that was dome sort of bug on my side (all libs are local in projects). There were two changes:
1. I have just reorganized the files (made separate script.js file)
2. I transferred the project to another machine

Some of that helped.

**Comment by mykolakozyr** [comment]
In my project i "fixed" by adding (below others) not existing function to the `openSidebar(e)` function. However, it seems like a bug.

**Comment by milas991** [comment]
Did anybody fix this?

**Comment by zedd45** [comment]
@mykolakozyr would you provide a code sample for what you meant by "adding 'not existing function' to `openSidebar(e)`?

**Comment by zedd45** [comment]
I'm closing this for now.  @mykolakozyr please feel free to share a sample of the code you used to fix this, and we can explore the issue as well as a potential fix.  

Thanks!
