### ISSUE TITLE
Leaflet >=1.1.0 L.DomEvent.fakestop()

### ISSUE THREAD

**Issue by adriennn** [Turbo87/leaflet-sidebar#54]
L.DomEvent._fakestop() is L.DomEvent.fakestop() since Lealfet 1.1.0, which causes issues with opening bootstrap dropdowns in the sidebar.

This should fix and allow backward compatibility in addTo() and removeFrom() methods (synthax untested)

`var fakeStop = L.version === '1.1.0' || '1.2.0' ? L.DomEvent.fakeStop || stop : L.DomEvent._fakeStop || stop;`

will try to make a PR soon, but if someone does it before me - it would be nice to have the stop events listeners activated and deactivated from an external private function to addTo() and removeFrom() so they are all in one place.

**Comment by Turbo87** [comment]
why not just `var fakeStop = L.DomEvent.fakeStop || L.DomEvent._fakeStop || stop;`?

**Comment by adriennn** [comment]
I've been using L.DomEvent._fakeStop() with 1.2.0 until I found out it just kept failing silently, but hopefully the evaluation dosen't fail silently?
