### ISSUE TITLE
Sidebar appear from the side when zoom level changed on the browser

### ISSUE THREAD

**Issue by onurtore** [Turbo87/leaflet-sidebar#55]
![e1](https://user-images.githubusercontent.com/20031290/33220699-55eae4e2-d15b-11e7-95df-47d2f5d28e93.png)
![e2](https://user-images.githubusercontent.com/20031290/33220700-560f9652-d15b-11e7-929b-23dd4e93b6dc.png)

When i zoom out with browser ,sidebar appears from the corner,is this problem fixed with the v2 ?

**Comment by adriennn** [comment]
do you have any custom css rules? Or did you set the width of the sidebar manually? Also note that v2 is a different mechanism than v1 as it's a collapsible sidebar.

**Comment by onurtore** [comment]
I set the width manually,its fixed when i used original.Thanks
