### ISSUE TITLE
Changing sidebar position on-the-fly

### ISSUE THREAD

**Issue by davkho** [Turbo87/leaflet-sidebar#56]
Hallo, 

trying to give the users an option to choice wether wants the sidebar on the right or left

this is how i defined my Sidebar:
```
var sidebar= L.control.sidebar('sidebar', {
	position: 'left',
	autoPan: false
});
map.addControl(sidebar);
sidebar.show();
```

what i tried in console:
```
>> sidebar.options.position = 'right'
<< "right"
>> sidebar.hide()
<< undefined
>> sidebar.show()
<< undefined
```

what i am expecting:
after calling `sidebar.show()` sidebar change the position to the right

what i am getting:
sidebar still on the left

I am using leaflet 1.3.1

**Comment by Turbo87** [comment]
dynamically changing the position of the sidebar is not currently supported

**Comment by zedd45** [comment]
Should we close this, then?

**Comment by zedd45** [comment]
I'm going to close this for now; it sounds like this is either a future or "won't fix."
