### ISSUE TITLE
Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by m-menon** [Turbo87/leaflet-sidebar#57]
Has anyone faced this error? leafletjs version 0.7.7, used with Mapquest maps. A bunch of other plugins do work so I guess I am missing a little something
Thanks

```
Uncaught TypeError: Cannot read property 'prototype' of undefined
    at L.Control.Sidebar.js:3
```

**Comment by zedd45** [comment]
It would help to have the entire stack trace, and perhaps a set of instructions, or ideally, a minimal repo where you can reproduce.

It may also be worth checking out the newer version: 
https://github.com/Turbo87/sidebar-v2

**Comment by zedd45** [comment]
I'm going to close this for now.  Please feel free to update the issue per my previous comment.
I did also notice that you mentioned Leaflet `v0.7.7`.  Have you tried upgrading to a more recent version?

**Comment by m-menon** [comment]
I think I managed to solve that problem. I can't remember how exactly but I'll post should I remember :) Thanks @zedd45

**Comment by zedd45** [comment]
Thank you, @m-menon!
