### ISSUE TITLE
Close button hidden due low z-index

### ISSUE THREAD

**Issue by themacboy** [Turbo87/leaflet-sidebar#66]
![image](https://user-images.githubusercontent.com/8063711/64763450-4beda700-d540-11e9-8284-bab388a15c2e.png)

to solve the problem I have set my own close class

.close {
   z-index: 800 !important;
}

**Comment by hdsnet** [comment]
Please merge ASAP!

**Comment by Turbo87** [comment]
for our default example `8` seems to be sufficiently high. if you have other requirements then it's totally fine to override the default styles with a higher `z-index` value in your app.
