### ISSUE TITLE
Deprecated include of L.Mixin.Events

### ISSUE THREAD

**Issue by hdsnet** [Turbo87/leaflet-sidebar#74]
I am getting a deprecated function warning:
"Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead."
![leaflet-deprecated](https://user-images.githubusercontent.com/2870558/77330357-891cc800-6d1f-11ea-849d-a7ef1fc87c1b.png)

**Comment by hdsnet** [comment]
Is this possible to fix?

**Comment by zedd45** [comment]
This should be fixed with #75. Please let me know if this isn't the case by reopening this issue (or starting a new one).
